Container nvidia build =  16972326
out dir is .
python   run_squad.py --init_checkpoint=/data/bert_large/bert_large_uncased.pt --do_train --train_file=/data/squad/v1.1/train-v1.1.json --train_batch_size=2  --do_lower_case  --bert_model=bert-large-uncased  --learning_rate=0.0  --seed=1  --num_train_epochs=2.0  --max_seq_length=384  --doc_stride=128  --output_dir=.  --vocab_file=/data/bert_large/bert-large-uncased-vocab.txt  --config_file=/data/bert_large/bert_config.json  --max_steps=100   |& tee ./logfile.txt
device: cuda n_gpu: 1, distributed training: False, 16-bits training: False
DLL 2020-10-27 23:39:01.475548 - PARAMETER Config : ["Namespace(amp=False, bert_model='bert-large-uncased', cache_dir=None, config_file='/data/bert_large/bert_config.json', disable_progress_bar=False, do_eval=False, do_lower_case=True, do_predict=False, do_train=True, doc_stride=128, eval_script='evaluate.py', fp16=False, gradient_accumulation_steps=1, init_checkpoint='/data/bert_large/bert_large_uncased.pt', json_summary='results/dllogger.json', learning_rate=0.0, local_rank=-1, log_freq=50, loss_scale=0, max_answer_length=30, max_query_length=64, max_seq_length=384, max_steps=100.0, n_best_size=20, no_cuda=False, null_score_diff_threshold=0.0, num_train_epochs=2.0, output_dir='.', predict_batch_size=8, predict_file=None, seed=1, skip_cache=False, skip_checkpoint=False, train_batch_size=2, train_file='/data/squad/v1.1/train-v1.1.json', use_env=False, verbose_logging=False, version_2_with_negative=False, vocab_file='/data/bert_large/bert-large-uncased-vocab.txt', warmup_proportion=0.1)"] 
DLL 2020-10-27 23:39:01.476064 - PARAMETER SEED : 1 
WARNING: Output directory . already exists and is not empty. ['utils.py', 'README.md', 'optimization.py', '.gitignore', 'triton', 'vocab', 'run_swag.py', 'Dockerfile', 'scripts', 'images', 'extract_features.py', '.gitmodules', 'requirements.txt', 'schedulers.py', 'create_pretraining_data.py', 'bind.sh', 'modeling.py', 'results', 'NOTICE', 'run_squad.py', 'processors', 'data', '.git', 'checkpoints', 'inference.py', 'file_utils.py', 'configurations.yml', 'run_glue.py', 'run_pretraining.py', 'bind_pyt.py', 'run.sub', 'bert_config.json', '.dockerignore', 'LICENSE', 'tokenization.py', 'logfile.txt', '__pycache__']
DLL 2020-10-27 23:39:18.990885 - PARAMETER loading_checkpoint : True 
DLL 2020-10-27 23:39:18.990984 - PARAMETER loaded_checkpoint : True 
DLL 2020-10-27 23:39:21.115453 - PARAMETER model_weights_num : 335150082 
DLL 2020-10-27 23:39:21.337996 - PARAMETER train_start : True 
DLL 2020-10-27 23:39:21.338090 - PARAMETER training_samples : 87599 
DLL 2020-10-27 23:39:21.338121 - PARAMETER training_features : 1033 
DLL 2020-10-27 23:39:21.338153 - PARAMETER train_batch_size : 2 
DLL 2020-10-27 23:39:21.338178 - PARAMETER steps : 87598.0 
Traceback (most recent call last):
  File "run_squad.py", line 1200, in <module>
    main()
  File "run_squad.py", line 1039, in main
    dllogger.log(step="time started -------------------------------------------------------------------------")
TypeError: log() missing 1 required positional argument: 'data'

real	0m21.451s
user	0m20.346s
sys	0m1.391s
DONE!
