usage: main.py [-h] [--data-backend BACKEND] [--interpolation INTERPOLATION]
               [--arch ARCH] [-j N] [--prefetch N] [--epochs N]
               [--run-epochs N] [--early-stopping-patience N]
               [--image-size IMAGE_SIZE] [-b N] [--optimizer-batch-size N]
               [--lr LR] [--lr-schedule SCHEDULE] [--end-lr END_LR]
               [--warmup E] [--label-smoothing S] [--mixup ALPHA]
               [--optimizer {sgd,rmsprop}] [--momentum M] [--weight-decay W]
               [--bn-weight-decay] [--rmsprop-alpha RMSPROP_ALPHA]
               [--rmsprop-eps RMSPROP_EPS] [--nesterov] [--print-freq N]
               [--resume PATH] [--static-loss-scale STATIC_LOSS_SCALE]
               [--dynamic-loss-scale] [--prof N] [--amp] [--seed SEED]
               [--gather-checkpoints GATHER_CHECKPOINTS]
               [--raport-file RAPORT_FILE] [--evaluate] [--training-only]
               [--no-checkpoints] [--jit {no,script}]
               [--checkpoint-filename CHECKPOINT_FILENAME] [--workspace DIR]
               [--memory-format {nchw,nhwc}] [--use-ema USE_EMA]
               [--augmentation {None,autoaugment}]
               [--gpu-affinity {none,socket,socket_single,socket_single_unique,socket_unique_interleaved,socket_unique_contiguous}]
               [--topk TOPK]
               DIR
main.py: error: argument --data-backend: invalid choice: 'syntetic' (choose from 'pytorch', 'synthetic', 'dali-gpu', 'dali-cpu')
['/opt/conda/bin/python', '-u', './main.py', '/data/imagenet', '--arch', 'resnet50', '--amp', '--static-loss-scale', '256', '--epochs', '2', '--prof', '100', '--batch-size', '1440', '--raport-file', 'benchmark.json', '--print-freq', '1', '--training-only', '--data-backend', 'syntetic']
['/opt/conda/bin/python', '-u', './main.py', '/data/imagenet', '--arch', 'resnet50', '--amp', '--static-loss-scale', '256', '--epochs', '2', '--prof', '100', '--batch-size', '1440', '--raport-file', 'benchmark.json', '--print-freq', '1', '--training-only', '--data-backend', 'syntetic']
DONE!
